# Generated by Django 5.2.8 on 2025-11-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False, verbose_name='题目ID')),
                ('author', models.CharField(max_length=100, verbose_name='题目作者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=255, verbose_name='题目标题')),
                ('content', models.TextField(blank=True, verbose_name='题目描述')),
                ('input_description', models.TextField(blank=True, verbose_name='输入描述')),
                ('output_description', models.TextField(blank=True, verbose_name='输出描述')),
                ('input_demo', models.TextField(blank=True, verbose_name='输入样例')),
                ('output_demo', models.TextField(blank=True, verbose_name='输出样例')),
                ('time_limit', models.IntegerField(default=1000, verbose_name='时间限制(ms)')),
                ('memory_limit', models.IntegerField(default=256, verbose_name='内存限制(MB)')),
                ('hint', models.TextField(blank=True, verbose_name='提示信息')),
                ('auth', models.IntegerField(choices=[(1, '公开题目'), (2, '私密题目'), (3, '比赛题目')], default=1, verbose_name='题目权限')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'problem',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ProblemData',
            fields=[
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stat', serialize=False, to='problems.problem', verbose_name='题目')),
                ('title', models.CharField(max_length=255, verbose_name='题目标题')),
                ('level', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='题目难度')),
                ('submission', models.IntegerField(default=0, verbose_name='提交总数')),
                ('ac', models.IntegerField(default=0, verbose_name='通过数')),
                ('tle', models.IntegerField(default=0, verbose_name='超时数')),
                ('mle', models.IntegerField(default=0, verbose_name='内存超限数')),
                ('ce', models.IntegerField(default=0, verbose_name='编译错误数')),
                ('pe', models.IntegerField(default=0, verbose_name='答案错误数')),
                ('tag', models.TextField(blank=True, verbose_name='题目标签')),
                ('auth', models.IntegerField(choices=[(1, '公开题目'), (2, '私密题目'), (3, '比赛题目')], default=1, verbose_name='题目权限')),
                ('score', models.IntegerField(default=100, verbose_name='题目分数')),
            ],
            options={
                'verbose_name': '题目统计',
                'verbose_name_plural': '题目统计',
                'db_table': 'problem_data',
            },
        ),
    ]
