# Generated by Django 5.2.8 on 2025-12-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='提交ID')),
                ('code', models.TextField(verbose_name='提交代码')),
                ('language', models.CharField(max_length=20, verbose_name='编程语言')),
                ('status', models.IntegerField(choices=[(0, 'Accepted'), (-1, 'Wrong Answer'), (1, 'Time Limit Exceeded'), (3, 'Memory Limit Exceeded'), (4, 'Runtime Error'), (5, 'Compile Error'), (6, 'System Error'), (7, 'Judging')], default=7, verbose_name='判题状态')),
                ('result', models.JSONField(default=dict, verbose_name='判题结果详情')),
                ('cpu_time', models.IntegerField(default=0, verbose_name='CPU时间(ms)')),
                ('memory', models.BigIntegerField(default=0, verbose_name='内存使用(字节)')),
                ('code_length', models.IntegerField(default=0, verbose_name='代码长度(字节)')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'db_table': 'submission',
                'ordering': ['-submit_time'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['auth'], name='problem_auth_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['problem_id'], name='problem_id_idx'),
        ),
        migrations.AddIndex(
            model_name='problemdata',
            index=models.Index(fields=['auth', 'level'], name='problem_data_auth_level_idx'),
        ),
        migrations.AddIndex(
            model_name='problemdata',
            index=models.Index(fields=['title'], name='problem_data_title_idx'),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.user', verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'user'], name='submission_problem_user_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submit_time'], name='submission_time_idx'),
        ),
    ]
