# Generated by Django 5.2.8 on 2025-12-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_rename_problem_data_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='ac',
            field=models.IntegerField(default=0, verbose_name='通过数(Accepted)'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='ce',
            field=models.IntegerField(default=0, verbose_name='编译错误数(Compile Error)'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='mle',
            field=models.IntegerField(default=0, verbose_name='内存超限数(Memory Limit Exceeded)'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='tle',
            field=models.IntegerField(default=0, verbose_name='超时数(Time Limit Exceeded)'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='wr',
            field=models.IntegerField(default=0, verbose_name='答案错误数(Wrong Answer)'),
        ),
    ]
