# Generated by Django 5.2.8 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_create_time_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contest_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='比赛ID(可空，空表示非比赛提交)'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest_id'], name='submission_contest_id_idx'),
        ),
    ]

