# Generated by Django 5.2.8 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0006_submission_contest_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="testcase_count",
            field=models.PositiveIntegerField(default=0, verbose_name="测试数据组数"),
        ),
    ]

