# Generated by Django 5.2.8 on 2025-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('motto', models.CharField(blank=True, default='', max_length=80, verbose_name='个性签名')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500, verbose_name='头像URL')),
                ('student_id', models.CharField(blank=True, default='', max_length=50, verbose_name='学号')),
                ('class_name', models.CharField(blank=True, default='', max_length=100, verbose_name='班级')),
                ('real_name', models.CharField(blank=True, default='', max_length=50, verbose_name='真实姓名')),
                ('status', models.CharField(choices=[('normal', '正常'), ('banned', '封禁')], default='normal', max_length=10, verbose_name='用户状态')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('total_submissions', models.IntegerField(default=0)),
                ('accepted_submissions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-created_at'],
            },
        ),
    ]
