# Generated by Django 5.2.8 on 2025-11-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='', max_length=1),
        ),
    ]
