# Generated by Django 5.2.8 on 2025-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('banned', '封禁')], default='normal', max_length=10, verbose_name='用户状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
