# Generated by Django 5.2.8 on 2025-12-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.AutoField(primary_key=True, serialize=False, verbose_name='比赛ID')),
                ('contest_name', models.CharField(max_length=255, verbose_name='比赛名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='比赛描述')),
                ('creator_id', models.IntegerField(verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'db_table': 'contest',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['creator_id'], name='contest_creator_id_idx'), models.Index(fields=['create_time'], name='contest_create_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContestStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('participant_count', models.PositiveIntegerField(default=0, verbose_name='参赛人数')),
                ('registration_count', models.PositiveIntegerField(default=0, verbose_name='报名人数')),
                ('submission_count', models.PositiveIntegerField(default=0, verbose_name='总提交次数')),
                ('problem_count', models.PositiveIntegerField(default=0, verbose_name='题目数量')),
                ('ac_submission_count', models.PositiveIntegerField(default=0, verbose_name='AC提交数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contest', models.OneToOneField(db_column='contest_id', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='contest.contest', verbose_name='比赛')),
            ],
            options={
                'verbose_name': '比赛统计信息',
                'verbose_name_plural': '比赛统计信息',
                'db_table': 'contest_statistics',
            },
        ),
        migrations.CreateModel(
            name='ContestPermissionConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('visibility', models.BooleanField(default=True, verbose_name='比赛是否可见')),
                ('show_rank', models.BooleanField(default=True, verbose_name='是否显示排行榜')),
                ('show_others_code', models.BooleanField(default=False, verbose_name='是否可查看他人代码')),
                ('show_testcase', models.BooleanField(default=False, verbose_name='是否显示测试用例')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contest', models.OneToOneField(db_column='contest_id', on_delete=django.db.models.deletion.CASCADE, related_name='permission_config', to='contest.contest', verbose_name='比赛')),
            ],
            options={
                'verbose_name': '比赛权限配置',
                'verbose_name_plural': '比赛权限配置',
                'db_table': 'contest_permission_config',
                'indexes': [models.Index(fields=['visibility'], name='contest_perm_visibility_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContestRuleConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('contest_type', models.CharField(choices=[('ACM', 'ACM'), ('IOI', 'IOI'), ('OI', 'OI')], default='ACM', max_length=10, verbose_name='赛制')),
                ('contest_mode', models.CharField(choices=[('公开赛', '公开赛'), ('私有赛', '私有赛')], default='公开赛', max_length=20, verbose_name='赛种')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='比赛密码(加密存储)')),
                ('penalty_time', models.PositiveIntegerField(default=20, verbose_name='罚时(分钟，默认20)')),
                ('language_limit', models.JSONField(blank=True, null=True, verbose_name='语言限制(JSON数组)')),
                ('allow_submit_after_end', models.BooleanField(default=False, verbose_name='结束后是否可提交')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contest', models.OneToOneField(db_column='contest_id', on_delete=django.db.models.deletion.CASCADE, related_name='rule_config', to='contest.contest', verbose_name='比赛')),
            ],
            options={
                'verbose_name': '比赛规则配置',
                'verbose_name_plural': '比赛规则配置',
                'db_table': 'contest_rule_config',
                'indexes': [models.Index(fields=['contest_type'], name='contest_rule_type_idx'), models.Index(fields=['contest_mode'], name='contest_rule_mode_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContestTimeConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('start_time', models.DateTimeField(verbose_name='比赛开始时间')),
                ('end_time', models.DateTimeField(verbose_name='比赛结束时间')),
                ('duration', models.PositiveIntegerField(verbose_name='比赛持续时间(分钟)')),
                ('register_start_time', models.DateTimeField(blank=True, null=True, verbose_name='报名开始时间')),
                ('register_end_time', models.DateTimeField(blank=True, null=True, verbose_name='报名结束时间')),
                ('status', models.CharField(choices=[('即将开始', '即将开始'), ('进行中', '进行中'), ('已结束', '已结束')], default='即将开始', max_length=20, verbose_name='比赛当前状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contest', models.OneToOneField(db_column='contest_id', on_delete=django.db.models.deletion.CASCADE, related_name='time_config', to='contest.contest', verbose_name='比赛')),
            ],
            options={
                'verbose_name': '比赛时间配置',
                'verbose_name_plural': '比赛时间配置',
                'db_table': 'contest_time_config',
                'indexes': [models.Index(fields=['start_time'], name='contest_time_start_time_idx'), models.Index(fields=['status'], name='contest_time_status_idx')],
            },
        ),
    ]
