# Generated by Django 5.2.8 on 2025-12-25 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        ('problems', '0004_alter_problemdata_ac_alter_problemdata_ce_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestAnnouncement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(max_length=255, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('is_important', models.BooleanField(default=False, verbose_name='是否重要(置顶)')),
                ('publisher_id', models.IntegerField(verbose_name='发布人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contest', models.ForeignKey(db_column='contest_id', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='contest.contest', verbose_name='比赛')),
            ],
            options={
                'verbose_name': '比赛公告',
                'verbose_name_plural': '比赛公告',
                'db_table': 'contest_announcement',
                'ordering': ['-is_important', '-create_time'],
                'indexes': [models.Index(fields=['contest', 'is_important', 'create_time'], name='contest_ann_important_idx'), models.Index(fields=['contest', 'create_time'], name='contest_ann_time_idx'), models.Index(fields=['publisher_id'], name='contest_ann_publisher_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('display_order', models.CharField(max_length=10, verbose_name='题目序号(ABC)')),
                ('display_title', models.CharField(max_length=255, verbose_name='比赛中显示的题目标题')),
                ('score', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='题目分数(IOI/OI赛制)')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='气球颜色(ACM赛制)')),
                ('accept_count', models.PositiveIntegerField(default=0, verbose_name='AC人数')),
                ('submit_count', models.PositiveIntegerField(default=0, verbose_name='提交次数')),
                ('first_blood_user_id', models.IntegerField(blank=True, null=True, verbose_name='一血用户ID')),
                ('first_blood_time', models.DateTimeField(blank=True, null=True, verbose_name='一血时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contest', models.ForeignKey(db_column='contest_id', on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contest.contest', verbose_name='比赛')),
                ('problem', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='problems.problem', verbose_name='题目')),
            ],
            options={
                'verbose_name': '比赛题目关联',
                'verbose_name_plural': '比赛题目关联',
                'db_table': 'contest_problem',
                'indexes': [models.Index(fields=['contest', 'display_order'], name='contest_problem_order_idx'), models.Index(fields=['contest', 'problem'], name='contest_problem_idx'), models.Index(fields=['first_blood_user_id'], name='contest_problem_fb_user_idx')],
                'unique_together': {('contest', 'display_order')},
            },
        ),
        migrations.CreateModel(
            name='ContestRank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='排名')),
                ('total_score', models.FloatField(default=0.0, verbose_name='总分(IOI/OI赛制)')),
                ('total_time', models.PositiveIntegerField(default=0, verbose_name='总罚时(分钟,ACM赛制)')),
                ('ac_count', models.PositiveIntegerField(default=0, verbose_name='AC题目数')),
                ('submit_count', models.PositiveIntegerField(default=0, verbose_name='提交次数')),
                ('problem_status', models.JSONField(default=dict, verbose_name='每题状态(JSON: {A: {status, time, score, tries}})')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contest', models.ForeignKey(db_column='contest_id', on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='contest.contest', verbose_name='比赛')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contest_ranks', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '比赛排名',
                'verbose_name_plural': '比赛排名',
                'db_table': 'contest_rank',
                'indexes': [models.Index(fields=['contest', 'rank'], name='contest_rank_contest_rank_idx'), models.Index(fields=['contest', 'user'], name='contest_rank_contest_user_idx'), models.Index(fields=['update_time'], name='contest_rank_update_time_idx')],
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('real_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='学号')),
                ('school', models.CharField(blank=True, max_length=255, null=True, verbose_name='学校')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('报名成功', '报名成功'), ('报名失败', '报名失败')], default='报名成功', max_length=20, verbose_name='报名状态')),
                ('is_star', models.BooleanField(default=False, verbose_name='是否打星选手')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contest', models.ForeignKey(db_column='contest_id', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contest.contest', verbose_name='比赛')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '比赛报名',
                'verbose_name_plural': '比赛报名',
                'db_table': 'contest_registration',
                'indexes': [models.Index(fields=['contest', 'user'], name='contest_reg_contest_user_idx'), models.Index(fields=['contest', 'register_time'], name='contest_reg_time_idx'), models.Index(fields=['status'], name='contest_reg_status_idx')],
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
