# Generated by Django 5.2.8 on 2026-03-19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0003_remove_participant_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestrank',
            name='rank',
        ),
        migrations.RemoveIndex(
            model_name='contestrank',
            name='contest_rank_contest_rank_idx',
        ),
    ]

