# -*- coding: utf-8 -*-

"""
Django settings for huebRE project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import pymysql
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env located at project root
load_dotenv(BASE_DIR / '.env')


def env_bool(key: str, default: bool = False) -> bool:
    """Helper to parse boolean env values."""
    value = os.getenv(key)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(key: str, default: int) -> int:
    """Helper to parse integer env values."""
    value = os.getenv(key)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 生产环境必须使用强随机密钥，不要使用默认值
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-pw^gfr(7ukiw%l@6&h+se-1+udczua98=kk3fdpk9#3a=tf-uq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)

allowed_hosts_raw = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_raw.split(',') if host.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
    'problems',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'huebRE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'huebRE.wsgi.application'

# database settings
MYSQL_DATABASE_NAME = os.getenv('MYSQL_DATABASE_NAME', 'onlinejudge')
MYSQL_CONNECTION = {
    'host': os.getenv('MYSQL_HOST', 'localhost'),
    'user': os.getenv('MYSQL_USER', 'root'),
    'password': os.getenv('MYSQL_PASSWORD', 'hueboj123'),
    'port': env_int('MYSQL_PORT', 3306),
    'charset': 'utf8mb4',
}


def ensure_mysql_database():
    """确保 MySQL 数据库存在，如果不存在则创建"""
    connection = None
    try:
        connection = pymysql.connect(
            host=MYSQL_CONNECTION['host'],
            user=MYSQL_CONNECTION['user'],
            password=MYSQL_CONNECTION['password'],
            port=MYSQL_CONNECTION['port'],
            charset=MYSQL_CONNECTION['charset'],
            autocommit=True,
        )
        with connection.cursor() as cursor:
            cursor.execute(
                f"""
                CREATE DATABASE IF NOT EXISTS `{MYSQL_DATABASE_NAME}`
                DEFAULT CHARACTER SET utf8mb4
                COLLATE utf8mb4_unicode_ci
                """
            )
    except pymysql.MySQLError as exc:
        raise ImproperlyConfigured(
            f"无法创建或连接数据库 `{MYSQL_DATABASE_NAME}`: {exc}"
        ) from exc
    finally:
        if connection:
            connection.close()


def ensure_database_and_tables():
    """确保数据库和表存在，如果不存在则创建（运行时调用）"""
    try:
        # 先确保数据库存在
        ensure_mysql_database()
        
        # 检查数据库连接是否正常
        from django.db import connection as db_connection
        db_connection.ensure_connection()
        
        # 检查 user 表是否存在
        with db_connection.cursor() as cursor:
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.tables "
                "WHERE table_schema = %s AND table_name = 'user'",
                [MYSQL_DATABASE_NAME]
            )
            table_exists = cursor.fetchone()[0] > 0
            
            if not table_exists:
                # 表不存在，运行迁移
                from django.core.management import call_command
                call_command('migrate', verbosity=0, interactive=False)
                
    except Exception as exc:
        # 如果出错，记录但不抛出异常，让视图层处理
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"数据库检查/创建失败: {exc}")
        raise  # 重新抛出异常，让调用者知道失败了


ensure_mysql_database()

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DATABASE_NAME,
        'USER': MYSQL_CONNECTION['user'],
        'PASSWORD': MYSQL_CONNECTION['password'],
        'HOST': MYSQL_CONNECTION['host'],
        'PORT': MYSQL_CONNECTION['port'],
        # 数据库连接设置 提升性能
        'CONN_MAX_AGE': 600, # 连接保持时间，单位秒
        'OPTIONS': {
            'charset': MYSQL_CONNECTION['charset'],
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 10, # 连接超时时间，单位秒
            'read_timeout': 10, # 读取超时时间，单位秒
            'write_timeout': 10, # 写入超时时间，单位秒
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 简易 JWT 配置
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_EXP_DELTA_SECONDS = env_int('JWT_EXP_DELTA_SECONDS', 7 * 24 * 60 * 60)  # 7 天

# CORS 跨域配置
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境允许所有源，生产环境应使用 CORS_ALLOWED_ORIGINS
CORS_ALLOW_CREDENTIALS = True  # 允许携带凭证（Cookie、Authorization 等）
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Minio/S3配置
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', 'minioadmin')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', 'minioadmin')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', 'http://localhost:9000')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'onlinejudge')
AWS_S3_USE_SSL = env_bool('AWS_S3_USE_SSL', False)  # 如果MinIO使用HTTP，设为False；HTTPS则True
AWS_S3_VERIFY = env_bool('AWS_S3_VERIFY', False)  # 如果使用自签名证书，设为False
AWS_S3_FILE_OVERWRITE = env_bool('AWS_S3_FILE_OVERWRITE', True)  # 如果设置为True，则文件覆盖；如果设置为False，则文件重命名
AWS_S3_OBJECT_PARAMETERS = {  # 能提升访问速度
    "CacheControl": "max-age=86400",
}
AWS_QUERYSTRING_AUTH = env_bool('AWS_QUERYSTRING_AUTH', False)  # 如果使用自签名证书，设为False

# 判题机配置
JUDGE_SERVER_URL = os.getenv('JUDGE_SERVER_URL', 'http://101.42.172.229:12358')
JUDGE_SERVER_TOKEN = os.getenv('JUDGE_SERVER_TOKEN', 'OYg4fMThGAjH80rojURhEz5GOBgSlMVm')