# Generated by Django 5.2.8 on 2025-12-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
