# Generated by Django 5.2.8 on 2026-03-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_discussion_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
    ]
